services:
  upskillapi:
    image: siwapan/upskill:5.25.9
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    # Mount โค้ดจากเครื่อง host ไปยัง container
    ports:
      - "3999:3000"
volumes:
  my_data:
    name: upload_custom_volume  # ตั้งชื่อ volume แบบกำหนดเอง